using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Odin.Component.CodeGen.Utils;

namespace Odin.Component.CodeGen.Generators.Impl;

[Generator]
public class ComponentDeclarationGenerator : AComponentIncrementalGenerator
{
    protected override void GenerateCode(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<StructDeclarationSyntax> structDeclarations
    )
    {
        var namespaceName = compilation.AssemblyName;

        var methodBody = structDeclarations
                        .Select(sds =>
                         {
                             var semanticModel = compilation.GetSemanticModel(sds.SyntaxTree);

                             var symbol = semanticModel.GetDeclaredSymbol(sds);

                             return symbol as INamedTypeSymbol;
                         })
                        .Where(s => s != null)
                        .Select(s => s!)
                        .Select(s =>
                         {
                             var fullName = s.OriginalDefinition.ToDisplayString();

                             var members = s.GetMembers();

                             var processedMembers = ComponentFieldProcessor.GetFieldDeclarations(members);

                             return $"""
                                             Component<{fullName}>()
                                                 .WithName("{fullName}")
                                                 {string.Join("\n\t\t\t", processedMembers)}
                                                 .Build();
                                     """;
                         });

        // foreach (var structDeclarationSyntax in structDeclarations)
        // {
        //     var semanticModel = compilation.GetSemanticModel(structDeclarationSyntax.SyntaxTree);
        //
        //     if (semanticModel.GetDeclaredSymbol(structDeclarationSyntax) is not INamedTypeSymbol structSymbol)
        //         continue;
        //
        //     //var namespaceName = structSymbol.ContainingNamespace.ToDisplayString();
        //
        //     //var structName = structDeclarationSyntax.Identifier.Text;
        // }

        var code = $@"
// <auto-generated/>

using System;
using System.Collections.Generic;
using Odin.Abstractions.Components.Declaration;
using Odin.Abstractions.Components.Declaration.Builder.States;

namespace {namespaceName};

public class ComponentDeclarations : AComponentDeclarations
{{
    protected override void Configure()
    {{
{string.Join("\n\n", methodBody)}
    }}
}}
";

        context.AddSource("ComponentDeclarations.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}